# Generated by Django 4.1.2 on 2024-06-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_makween', '0002_vehiculo_delete_alumno_delete_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=60)),
            ],
        ),
    ]
