# Generated by Django 4.1.2 on 2024-07-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_makween', '0006_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
