# Generated by Django 4.1.2 on 2024-07-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_makween', '0009_carrito_carritoproducto_carrito_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
    ]
