# Generated by Django 4.1.2 on 2024-07-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller_makween', '0011_carrito_alter_producto_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
